# Generated by Django 6.1 on 2026-09-03 04:13

import habits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=habits.models.timezone_choices, default='UTC', max_length=64),
        ),
    ]
