# Generated by Django 6.1 on 2026-09-04 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='repeat every N days'),
        ),
    ]
