# Generated by Django 6.1 on 2026-09-04 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_interval_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval_days',
            field=models.PositiveIntegerField(default=1, help_text='1 = every day, 3 = every third day (1st, 4th, 7th)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='repeat every N days'),
        ),
    ]
